### ISSUE TITLE
Marketplace

### ISSUE THREAD

**Issue by Guiriou** [Foris-master/orange-money-sdk#1]
Is it possible to create a marketplace with this api?

**Comment by Foris-master** [comment]
Hi @Guiriou , of course you can use it in a marketplace app

**Comment by Guiriou** [comment]
I'm in Madagascar, i want to create a site that will have many sub-merchants. When someone buys from a sub-merchant, the payment will be split, I take my commission and the rest to the sub-merchant's orange money account. Is it possible?

**Comment by Foris-master** [comment]
ok I guest, the current api target web payment (customer to server money transfer ), it does not support the transfer of money to a customer. For your issue a workaround would be to keep a register of transaction (a table in database) and use another payment method to transfer money to your merchants (eg paypal or stripe).
