### ISSUE TITLE
Is this still up to date?

### ISSUE THREAD

**Issue by Killa8** [Foris-master/orange-money-sdk#2]
Hi, good job here. I'm in Cameroon and willing to integrate this code into my project. Wanted to know if it is up to date with the current orange API (i think it's still after going through the code and the API documentation). 

And it seems kind of complex and requires many dependencies. I'm not much of a coder maybe that's why i'm having issues. Hopefully you could help, thanks

**Comment by Foris-master** [comment]
Hi @Killa8 ,
yes the project is up to date. The SDK is simple in that it exposes a single class. But you should contact the orange team to get a merchant key and an auth header.

**Comment by Killa8** [comment]
> Hi @Killa8 ,
> yes the project is up to date. The SDK is simple in that it exposes a single class. But you should contact the orange team to get a merchant key and an auth header.

Thaks for the fast reply. I do posses the Header and key, all the credentials. My problem is there is actually no .env file after i had cloned the repo (which turns out to be a Docker extension?) so i don't know how to process from there, especially since i don't want to start modifying the code and set all to static variables (bad coding habits haha). YOur help will be greatly appreciated

**Comment by Foris-master** [comment]
are you using a php framework (like laravel ou symphony) ? 

- if yes , you should have a .env config file in your project. 

- if not , are you using a package manager? ( like composer, it seem like no)

-  if yes use it to install the package [php dotenv](https://github.com/vlucas/phpdotenv) also it to install [the orange money sdk (packagist link) ](https://packagist.org/packages/foris-master/orange-money-sdk).
- if not, you do not need the dotenv package to enable enviroment variable in php ( you could use putenv, getenv built in function) but for the sdk package i advise you to enable composer to your project

**Comment by Killa8** [comment]
Thanks again for the help. I do have composer (I don’t use latavel or other MVCs since I don’t do PHP), that’s why I am a bit of confused. I will give it a shot ASAP. Thanks

**Comment by saintcreators** [comment]
Hi, the package is installed via composer with dotenv package too. But when i try to intialise a class, it is recognised by Vs Code's Intelliphense as an existing class, but when ran i a browser via lamp throws an error. 
I'm working on Ubuntu 19 LTs with VS Code and Xampp

>`
Fatal error: Uncaught Error: Call to a member function getBody() on string in /home/blckpatcher/Documents/Projet Felix/website/Wandastickers/vendor/foris-master/orange-money-sdk/src/OmSdk.php:30 Stack trace: #0 /home/blckpatcher/Documents/Projet Felix/website/Wandastickers/vendor/foris-master/orange-money-sdk/src/OmSdk.php(40): Foris\OmSdk\OmSdk->getAccesToken() #1 /home/blckpatcher/Documents/Projet Felix/website/Wandastickers/index.php(11): Foris\OmSdk\OmSdk->webPayment(Array) #2 {main} thrown in /home/blckpatcher/Documents/Projet Felix/website/Wandastickers/vendor/foris-master/orange-money-sdk/src/OmSdk.php on line 30`

**Comment by Foris-master** [comment]
@saintcreators  please reference a new issue for this with your working enviroment details.

**Comment by Killa8** [comment]
Hi, it works perfectly and great ! Thanks a lot for the great work, once i figured out how to get it running all was smooth. All is handled automatically and it's saving me a great load of time. I just need to attach it to the front end via AJAX and link to a database, since it seems to me the Orange doesn't register the payments made. Thanks again !

**Comment by Foris-master** [comment]
@Killa8  thanks , i will close the issue now !

**Comment by Killa8** [comment]
Sorry one last question, how do i pass into production mode? No real purchases can be made with the currency set in OUV, and setting it to CF doesn't work. Any clue please?
